<div class="coupn-area">
	<?php if (!$this->success && !empty($this->message)){ ?>
    	<div class="alert alert-danger">
    		<p><?php echo $this->message;?></p>
    	</div>
    <?php }elseif($this->success){?>
    	<div class="alert alert-success">
    		<p><?php echo $this->message?></p>
    	</div>
    <?php }?>
    
    <div class="catagory-title cat-tit-5 mb-20">
        <h3>Coupon</h3> 
        <p>Enter your coupon code if you have one.</p>
    </div>   
    
    <?php 
        $form = $this->couponForm;
        $form->setAttribute('method', 'POST');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->DemoSiteFieldCollection($form);
    ?>
    
    <button class="btn-def btn2"><strong>VALIDATE COUPON</strong></button>
    
	<?php echo $this->form()->closeTag(); ?>
</div>