<?php if (!$this->checkoutErrorMsg){ ?>

	<?php if ($this->checkoutHasErr){ ?>
    	<div class="alert alert-danger">
    		<strong>Product error(s) occured.</strong> Error message appeared under the name of the Product.
    	</div>
    <?php } ?>
    
    <div class="row">
        <div class="col-xs-12">
            <div class="checkout-payment-area">
                <div class="checkout-total mt20">
                   	<h3>Your order</h3>
                   	<form action="#" method="post">
                       	<div class="table-responsive">
                            <table class="checkout-area table">
                                <thead>
                                    <tr class="cart_item check-heading">
                                        <td class="ctg-type">Product</td>
                                        <td class="cgt-des text-center">Quantity</td>
                                        <td class="cgt-des">Unit Price</td>
                                        <td class="cgt-des">Discount</td>
                                        <td class="cgt-des">Total</td>
                                    </tr>
                                </thead>
                                <tbody>
                                	<?php 
                            		    $totalQty = 0;
                            		    foreach ($this->checkoutCart As $val){
                            	    ?>
                            	    <tr class="cart_item check-item prd-name">
                                        <td class="ctg-type"> 
                                        	<?php echo $val['var_product_name'].' <span class="hidden-xs">('.$val['var_sku'].')</span>' ?>
                                        	<?php 
                            				    if (!empty($val['var_err']))
                            				    {
                            				        echo '<div class="text-danger">'.$val['var_err'].'</div>';
                            				    }
                        				    ?>
                                    	</td>
                                        <td class="cgt-des text-center"> <?php echo $val['var_quantity']?></td>
                                        <td class="cgt-des"> <?php echo $val['var_currency_symbol'].$val['var_price']?></td>
                                        <td class="cgt-des"> <?php echo !empty($val['var_discount'])? $val['var_currency_symbol'].$val['var_discount'] : ''?></td>
                                        <td class="cgt-des"> <?php echo $val['var_currency_symbol'].$val['var_total']?></td>
                                    </tr>
                                    
                            	    <?php 
                            		        $totalQty += $val['var_quantity']; 
                            		    }
                            	    ?>
                            	    
                                    <tr class="cart_item">
                                        <td class="ctg-type">Subtotal</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td class="cgt-des"><?php echo $this->checkoutCurrency.$this->checkoutCartSubTotal?></td>
                                    </tr>
                                    
                                    <?php if (!empty($this->checkoutCartDiscount)){?>
                                        <tr class="cart_item">
                                            <td class="ctg-type">Order discount</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td class="cgt-des"><?php echo $this->checkoutCurrency.$this->checkoutCartDiscount; ?></td>
                                        </tr>
                                    <?php }?>
                                    
                                    <tr class="cart_item">
                                        <td class="ctg-type">Shipping</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td class="cgt-des"><?php echo $this->checkoutCurrency.$this->checkoutShipping?></td>
                                    </tr>
                                    <tr class="cart_item">
                                        <td class="ctg-type crt-total"> Total</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td class="cgt-des crt-total"><?php echo $this->checkoutCurrency.$this->checkoutCartTotal?></td>
                                    </tr>
                                </tbody>
                        	</table>
                        </div>
                	</form>
            	</div>
            </div>
        </div>
        
        <div class="col-md-12 col-xs-12">
        	<a class="btn-def btn2" href="<?php echo $this->prevStep_link?>">Previous</a>
        	<?php if (!$this->checkoutHasErr){ ?>
        		<a class="btn-def btn2 pull-right" href="<?php echo $this->nextStep_link?>">Next</a>
            <?php } ?>
        </div>
        
    </div>
<?php }else{ ?>

	<div class="alert alert-danger">
		<strong><?php echo $this->checkoutErrorMsg?></strong>
	</div>
	
	<?php if ($this->prevStep_link){ ?>
		<a class="btn-def btn2" href="<?php echo $this->prevStep_link?>">Previous</a>
	<?php } ?>
	
<?php } ?>