<?php if ($this->order){ ?>
    <div class="checkout-payment-area order-det">
    	<div class="c-order-details-box">
    		<h3>Order Confirmation</h3>
    		<div class="row">
    			<?php if (!empty($this->orderErrMsg)){ ?>
					<div class="alert alert-danger">
            			<strong><?php echo $this->orderErrMsg ?></strong>
            		</div>
    			<?php } ?>
    			<div class="col-xs-12 col-sm-9">
    				<div class="reference-box">
    					<span>Reference:</span>
    					<span class="ref-num r-highlight"><?php echo $this->order['orderReference'] ?></span>
    				</div>
    				<div class="order-date-box">
    					Placed on <?php echo date("F, d Y" ,strtotime($this->order['orderDate'])) . ' at ' .date("H:iA" ,strtotime($this->order['orderDate'])); ?>
    				</div>
    			</div>
    		</div>
    		<div class="c-order-details-content">
    			<form action="#" method="post">
    			    <div class="table-responsive">
    			        <table class="checkout-area table c-table-lists">
    			            <thead>
    			                <tr class="cart_item check-heading">
    			                    <td class="ctg-type">Product</td>
    			                    <td class="ctg-type text-center">Unit Price</td>
    			                    <td class="ctg-type text-center"><span class="desktop-only">Quantity</span><span class="mobile-only">Qty</span></td>
    			                    <td class="ctg-type text-center"><span class="desktop-only">Discount</span><span class="mobile-only">Disc</span></td>
    			                    <td class="ctg-type">Total</td>
    			                </tr>
    			            </thead>
    			            <tbody>
    			            <?php foreach($this->orderBasket as $item){ ?>
            					<tr class="cart_item check-item prd-name">
    			                    <td class="ctg-type c-product-img">
    			                    	<div class="img-box modified">
    			                     		<img src="<?php echo $item->product_image ?>" alt="">
    					                    <div class="c-product-sku-box">
    						                    <span><?php echo $item->obas_product_name?></span><span class="c-product-sku">(<?php echo $item->obas_sku?>)</span>
    					                    </div>
    				                    	<div class="mobile-only">
    						                    <div class="c-product-sku-box">
    							                    <span class="c-product-sku-txt">SKU</span>
    							                    <span class="c-product-sku"><?php echo $item->obas_sku?></span>
    						                    </div>
    				                     		<span class="c-product-title"><?php echo $item->obas_product_name?></span>
    				                    	</div>
    			                    	</div>
    			                     </td>
    			                    <td class="ctg-type text-center"> <?php echo $item->cur_symbol.number_format($item->obas_price_net, 2) ?> </td>
    			                    <td class="ctg-type text-center"> <?php echo $item->obas_quantity?>  </td>
    			                    <td class="ctg-type text-center"> <?php echo ($item->discount) ? $item->cur_symbol.number_format($item->discount, 2) : ''?>  </td>
    			                    <td class="ctg-type"> <?php echo $item->cur_symbol.number_format(($item->obas_price_net * $item->obas_quantity) - $item->discount, 2)?> </td>
    			                </tr>
            					<?php } ?>
    			            </tbody>
    			        </table>
    			    </div>
    			    <div class="clearfix">
    				    <div class="c-order-number-box">
    				    	<div class="c-order-number-content">
    							<div class="c-order-numbers-row clearfix">
    								<div class="c-order-name">
    									<span>Subtotal</span>
    								</div>
    								<div class="c-oder-number">
    									<span><?php echo $this->order['orderCurrency'].number_format($this->order['orderSubtotal'], 2) ?></span>
    								</div>
    							</div>
    							<?php if (!empty($this->order['orderCouponDetails'])){ ?>
        							<div class="c-order-numbers-row clearfix">
        								<div class="c-order-name">
        									<span>Discount</span>
        								</div>
        							</div>
        							<div class="c-order-numbers-row clearfix">
        								<?php 
        								foreach($this->order['orderCouponDetails'] as $coupon){
        								    
        								?>
        								<div class="c-order-name">
        									<div class="c-order-mini">
        										<span>Code: <?= ($coupon['couponCode']) ? '<em>('.$coupon['couponCode'].')</em>' : '' ?></span>
        									</div>
        								</div>
        								<div class="c-oder-number">
        									<span><?= !empty($coupon['couponDiscount'])? '-'.$this->order['orderCurrency']. '' .number_format($coupon['couponDiscount'], 2) : $this->order['orderCurrency'].'0'; ?></span>
        								</div>
        								<?php } ?>
        							</div>
    							<?php } ?>
    							<div class="c-order-numbers-row clearfix">
    								<div class="c-order-name">
    									<span>Shipping</span>
    								</div>
    								<div class="c-oder-number">
    									<span><?php echo $this->order['orderCurrency'].number_format($this->order['orderSippingTotal'], 2) ?></span>
    								</div>
    							</div>
    							<div class="c-order-numbers-row clearfix">
    								<div class="c-order-name b-total">
    									<span>Total</span>
    								</div>
    								<div class="c-oder-number b-total">
    									<span><?php echo  $this->order['orderCurrency'].number_format($this->order['orderTotal'], 2) ?></span>
    								</div>
    							</div>
    				    	</div>
    				    </div>
    			    </div>
    			</form>
    		</div>
    	</div>
    </div>
    <br>
	<div class="ship-add">
		<div class="row">
			<div class="col-xs-12 col-md-6">
				<div class="order-address">
					<?= $this->orderAddressView ?>
				</div>
			</div>
		</div>
	</div>
<?php }else{ ?>
	<div class="alert alert-warning">
		<p>No result</p>
	</div>
<?php } ?>