<?php if ($this->checkoutHasErr):?>
	<div class="alert alert-danger">
		<strong>Product error(s) occured.</strong> Error message appeared under the name of the Product.
	</div>
<?php endif;?>
<!-- cart are start-->
<div class="cart-page-area">
   	<form id="checkout-cart" method="POST">
       	<div class="table-responsive mb-20">
            <table class="shop_table-2 cart table">
                <thead>
                    <tr>
                        <th class="product-thumbnail">Image</th>
                        <th class="product-name"><span class="desktop-only">Product Name</span><span class="mobile-only">Product</span></th>
                        <th class="product-price"><span class="desktop-only">Unit Price</span><span class="mobile-only">Price</span></th>
                        <th class="product-quantity"><span class="desktop-only">Quantity</span><span class="mobile-only">Qty</span></th>
                        <th class="product-price"><span class="desktop-only">Discount</span><span class="mobile-only">Disc</span></th>
                        <th class="product-subtotal">Total</th>
                        <th class="product-remove"><span class="desktop-only">Remove</span></th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                        foreach($this->checkOutCart as $item)
                        {
                            $productImg = ($item['product_img']) ? '<img src="'.$item['product_img'].'" alt="">' : '';
                            $discount = !empty($item['var_discount'])? $item['var_currency_symbol'].number_format($item['var_discount'], 2) : '';
                            echo '<tr>';
                            echo    '<td class="item-img">'.$productImg.'</td>';
                            echo    '<td class="item-title">'.$item['product_name'].' <span class="c-product-sku desktop-only desk-inline">('.$item['var_sku'].')</span>';
                                if (!empty($item['var_err']))
                                {
                                    echo '<div class="text-danger">'.$item['var_err'].'</div>';
                                }
                            echo    '</td>';
                            echo    '<td class="item-price" data-price="'.$item['var_price'].'">'.$item['var_currency_symbol'].$item['var_price'].'</td>';
                            echo    '<td class="item-qty">
                                        <div class="cart-quantity">
                                            <div class="product-qty">
                                                <div class="cart-quantity">
                                                    <div class="cart-plus-minus">
                                                        <div class="dec qtybutton desktop-only">-</div>
                                                        <div class="inc qtybutton mobile-only">+</div>
                                                        <input type="text" value="'.$item['var_quantity'].'" name="m_cc_var_qty['.$item['var_id'].']" class="cart-plus-minus-box" data-maxvalue="9999">
                                                        <div class="inc qtybutton desktop-only">+</div>
                                                        <div class="dec qtybutton mobile-only">-</div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>';
                            echo    (!empty($this->checkoutErrors[$item['var_id']])) ? '<p class="text-danger">'.$this->checkoutErrors[$item['var_id']].'</p>' : '';
                            echo    '</td>';
                            echo    '<td class="item-discount" data-value="'.$item['var_discount_value'].'" data-percentage="'.$item['var_discount_percentage'].'" data-usable-qty="'.$item['var_discount_usable_qty'].'">'.$discount.'</td>';
                            echo    '<td class="total-price" data-currency="'.$item['var_currency_symbol'].'"><strong>'.$item['var_currency_symbol'].number_format($item['var_total'], 2).'</strong></td>';
                            echo    '<td class="remove-item"><a href="'.$this->MelisLink($this->idPage, true).'?m_cc_var_remove='.$item['var_id'].'"><i class="fa fa-trash-o"></i></a></td>';
                            echo '</tr>';
                        }
                    ?> 
                </tbody>
            </table>
        </div>
 	</form>   
    <div class="cart-bottom-area">
        <div class="row">
        	<div class="col-xs-12">
        		<div class="update-continue-btn text-right pb-20">
                	<?php if (!empty($this->checkOutCart)):?>
                    	<button class="btn-def btn2 update-checkout-cart"><strong>UPDATE CART</strong></button>
                    <?php endif;?>
                </div>
        	</div>
            <div class="col-md-8 col-sm-7 col-xs-12">
                <div class="update-coupne-area">
                	<?php if (!empty($this->checkOutCart)):?>
                		<?php echo $this->checkoutCoupon?>
                	<?php endif;?>
                </div>
            </div>
            <div class="col-md-4 col-sm-5 col-xs-12">
                <div class="cart-total-area">
                    <div class="catagory-title cat-tit-5 mb-20 text-right">
                            <h3>Cart Totals</h3> 
                     </div>
                     <div class="sub-shipping">
                        <p>Subtotal <span><?php echo $this->checkOutCurrency.$this->checkOutCartSubTotal ?></span></p>
                        <?php 
                            if ($this->checkoutHasCoupon){
                                    
                                if (!empty($this->checkOutCartDiscountInfo))
                             	{
                             	    echo '<p>Order discount </p>';
                             	    foreach($this->checkOutCartDiscountInfo as $discInfo){
                             	        echo '<p>';
                             	        echo '(-'.$discInfo['details'].')';
                             	        echo '<span>';
                             	        echo $this->checkOutCurrency.$discInfo['amount'];
                                        echo '</span>';
                                        echo '</p>';
                             	    }
                             	    
                             	}
                         	}
                     	?>
                     </div>
                     <div class="process-cart-total">
                         <p>Total <span><?php echo $this->checkOutCurrency.$this->checkOutCartTotal ?></span></p>
                     </div>
                     <?php if ($this->checkOutCart):?>
                    	<div class="process-checkout-btn text-right">
                            <a class="btn-def btn2" href="<?php echo $this->nextStep_link?>">Process To Checkout Addresses</a>
                        </div>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- cart are end-->