<div class="container">
    <div class="row">
        <!-- Registration Start -->
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1 lr2">
        	<div class="alert alert-info checkout-payment-info">
    			<h3><i class="fa fa-info-circle" aria-hidden="true"></i> <small>This payment form is for testing only.</small></h3>
                <p>Use this fake card in order to confirm your payment:</p>
                <ul>
                	<li>1111222233334444 / 123</li>
                	<li>Expiration date in the future</li>
                </ul>
    		</div>
        	<?php 
            	$form = $this->fakePaymentForm;
            	$form->setAttributes(array(
                        'method' => 'GET',
                        'action' => '/MelisDemoCommerce/ComCheckout/confirmPayment',
                    ));
            	$form->prepare();
            	echo $this->form()->openTag($form);
        	?>
            	<div class="login-reg registration-form">
                	<h3>Payment API Form</h3>
            		<div class="alert alert-danger <?php echo (!$this->hasErr) ? 'hidden' : '' ?> ">
            			<strong>Oppss!</strong> Something went wrong, please try again.
            		</div>
            		<?php
                        echo $this->DemoSiteFieldCollection($form);
                    ?>
                </div>
                <div class="frm-action">
                    <div class="input-box tci-box">
                        <button class="btn-def btn2">Submit</button>
                    </div>
                </div>
            <?php 
                echo $this->form()->closeTag();
            ?>
		</div>
    </div>
</div>