<div id="delivery-address-form-messages">
    <div class="alert alert-success hidden">
    	<strong>Success!</strong> Delivery address has been successfully saved.
    </div>
    <div class="alert alert-danger hidden">
    	<strong>Error!</strong> An error(s) occured.
    </div>
</div>
<?php
if($this->showSelectAddressData) {
    $selAddrForm = $this->selectAddressForm;
    $selAddrForm->prepare();
    $selAddrForm->get('del_addr_id')->removeAttribute('onchange');
    echo $this->form()->openTag($selAddrForm);
    echo $this->formCollection($selAddrForm);
    echo $this->form()->closeTag();
}
?>
<?php

	$form = $this->deliveryAddress;
	$form->setAttribute('id', 'delivery-address-form');
	$form->setAttribute('method', 'post');
	$form->prepare();
	echo $this->form()->openTag($form); 
    echo $this->DemoSiteFieldCollection($form);
?>
<div class="text-right">
    <button type="button" class="btn-def btn2 pull-left delete-address" data-form="delivery-address-form" data-type="delivery">Delete Delivery Address</button>
    <button type="button" class="btn-def btn2" id="save-delivery-address" data-form="delivery-address-form" data-type="delivery">Save Delivery Address</button>
</div>
<?php
	echo $this->form()->closeTag();

?>
