<!-- Account Area Start -->
<div class="account-area ptb-80">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-push-3 col-xs-12">
                <div class="login-reg reset-pass">
                    <h3>Give us your account's email and we will send you a link to reset your password</h3>
                    <div class="alert alert-success hidden">
            			<strong>Success!</strong> An email has been sent to your inbox.
            		</div>
            		<div class="alert alert-danger hidden">
            			<strong>Error!</strong> An error has occured, please try again.
            		</div>
                    <?php 
                        $form = $this->lostPassword;
                        $form->setAttribute('id', 'lost-password-form');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->DemoSiteFieldCollection($form);
                    ?>
                    <div class="input-box mb-15">
                        <button type="submit" class="btn-def btn2 fw">Submit</button>
                    </div>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Account Area End -->