<?php
    $order = $this->returnProducts;
    if (!empty($order)){
?>
    <div class="checkout-payment-area order-det">
    	<div class="c-order-details-box">
    		<h3>Order: Return Products</h3>
            <div class="row">
                <div class="col-xs-12 col-sm-9">
                    <div class="reference-box">
                        <span>Reference:</span>
                        <span class="ref-num r-highlight"><?= $reference = !empty($order['reference'])? $order['reference'] : ''; ?></span>
                    </div>
                    <div class="order-date-box">
                        Placed on <?= $date = !empty($order['date'])? date("F, d Y" ,strtotime($order['date'])) . ' at ' .date("H:iA" ,strtotime($order['date'])): ''; ?>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-3">
                    <div class="status-box">
                        <span>Status:</span>
                        <span class="status r-highlight"><?= $status = !empty($order['status'])? $order['status']: ''; ?></span>
                    </div>
                </div>
            </div>
            <div class="c-order-return-product-content">
                <div class="table-responsive">
                    <table class="checkout-area table c-table-lists">
                        <thead>
                        <tr class="cart_item check-heading">
                            <td class="ctg-type">Product</td>
                            <td class="ctg-type text-center">Unit Price</td>
                            <td class="ctg-type text-center"><span class="desktop-only">Quantity</span><span class="mobile-only">Qty</span></td>
                            <td class="ctg-type text-center"><span class="desktop-only">Discount</span><span class="mobile-only">Disc</span></td>
                            <td class="ctg-type text-center"> Returns</td>
                            <td class="ctg-type"> Total</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        if(!empty($order['items'])){
                            foreach($order['items'] as $item){
                                ?>
                                <tr class="cart_item check-item prd-name" id="variant-<?= $item['variant_id'];?>">
                                    <td class="ctg-type c-product-img">
                                        <div class="img-box modified">
                                            <img src="<?= $item['productImage']?>" alt="">
                                            <div class="c-product-sku-box">
                                                <span><?= $item['productName']?></span><span class="c-product-sku">(<?= $item['sku']?>)</span>
                                            </div>
                                            <div class="mobile-only">
                                                <div class="c-product-sku-box">
                                                    <span class="c-product-sku-txt">SKU</span>
                                                    <span class="c-product-sku"><?= $item['sku']?></span>
                                                </div>
                                                <span class="c-product-title"><?= $item['productName']?></span>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="ctg-type text-center"> <?= $item['currency']. '' .number_format($item['price'], 2) ?> </td>
                                    <td class="ctg-type text-center"> <?= $item['quantity']?>  </td>
                                    <td class="ctg-type text-center"> <?= ($item['discount'])? $item['currency']. '' .number_format($item['discount'], 2) : '' ?>   </td>
                                    <td class="ctg-type text-center"><p>Returned: <span class="returned-product"><?= $item['returnedProduct']; ?></span><br><?= ($item['remainingQtyToReturn'] <= 0) ? '' : '<span data-variantid="'.$item['variant_id'].'" data-rm-pr="'.$item['remainingQtyToReturn'].'" data-sku="'.$item['sku'].'" class="return-product-show-form">Return product</span>';?></p></td>
                                    <td class="ctg-type"> <?= $item['currency']. '' .number_format($item['total'], 2)?> </td>
                                </tr>
                                <?php
                            }
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
    	</div>
    </div>
    <div class="order-return-product-msg-form">
        <br>
        <div style="margin-bottom: 20px;">
            <span class="alert alert-success hidden return-msg-status-success">Request submitted successfully</span>
            <span class="alert alert-danger hidden return-msg-status-failed">An error occurred while sending the form. Please contact the support</span>
        </div>
        <div class="rp-msg-form-cont hidden">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <h4>You wish to return this product, please fill the form:</h4>
                    <?php
                    $form = $this->addMessageForm;
                    $form->prepare();
                    echo $this->form()->openTag($form);

                    foreach ($form->getElements() As $key => $val)
                    {
                        echo '<div class="form-group row" style="margin-bottom:7px;">';

                        if ($val->getLabel())
                        {
                            $required = '';
                            if(!empty($val->getAttribute('required'))){
                                $required = ' <sup>*</sup>';
                            }
                            echo $this->formLabel()->openTag($val);
                            echo $val->getLabel();
                            echo $required;
                            echo $this->formLabel()->closeTag();
                        }

                        echo '<div class="col-md-8">';
                        echo $this->formElement($val, array('class' => 'form-control'));
                        echo $this->formElementErrors($val, array('class' => 'default-form-err-msg-plugin text-danger'));
                        echo '</div>';
                        echo '</div>';
                    }
                    echo '<button type="submit" class="btn btn-default">'.$this->translate('Submit request for return').'</button>';
                    echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
    </div>
    <br>
<?php } else { ?>

<?php } ?>
