<!-- Account Area Start -->
<div class="account-area ptb-80">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-push-3 col-xs-12">
                <div class="login-reg reset-pass">
                    <?php
                    if ($this->isValidKey) { ?>
                        <h3>Create a new password</h3>
                        <div class="alert alert-success hidden">
                            <strong>Success!</strong> Password has been successfully changed. Routing you to the login page.
                        </div>
                        <div class="alert alert-danger hidden">
                            <strong>Error!</strong> An error has occured, please try again.
                        </div>
                    <?php
                        $form = $this->lostPasswordReset;
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->DemoSiteFieldCollection($form);
                        ?>
                        <div class="input-box mb-15">
                            <button type="submit" class="btn-def btn2 fw" id="lost-password-btn">Submit</button>
                        </div>
                        <?php
                        echo $this->form()->closeTag();
                    }
                    else { ?>
                        <h3>Password Reset</h3>
                        <div class="alert alert-danger">
                            <strong><?= $this->message; ?>
                        </div>
                    <?php
                    }?>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- Account Area End -->