<?php 
$order = !empty($this->order)? $this->order : $this->layout()->dummyOrder;

if(!empty($order)){
$couponCode = '';
$discount = 0;
$discountPercent = '';
if(!empty($order['coupon'])){
    $couponCode = $order['coupon'];
    if(!empty($order['coupon_percentage'])){
        $discount = $order['subTotal'] * ($order['coupon_percentage']/100);
        $discountPercent = '-'.$order['coupon_percentage'] .'%';
    }else{
        $discount = $order['coupon_value'];
    }
}
?>
<div class="checkout-payment-area order-det">
	<div class="c-order-details-box">
		<h3>Order details</h3>
		<div class="row">
			<div class="col-xs-12 col-sm-9">
				<div class="reference-box">
					<span>Reference:</span>
					<span class="ref-num r-highlight"><?= $reference = !empty($order['reference'])? $order['reference'] : ''; ?></span>
				</div>
				<div class="order-date-box">
				
					Placed on <?= $date = !empty($order['date'])? date("F, d Y" ,strtotime($order['date'])) . ' at ' .date("H:iA" ,strtotime($order['date'])): ''; ?>
				</div>
			</div>
			<div class="col-xs-12 col-sm-3">
				<div class="status-box">
					<span>Status:</span>
					<span class="status r-highlight"><?= $status = !empty($order['status'])? $order['status']: ''; ?></span>
				</div>
			</div>
		</div>
		<div class="c-order-details-content">
			<form action="#" method="post">
			    <div class="table-responsive">
			        <table class="checkout-area table c-table-lists">
			            <thead>
			                <tr class="cart_item check-heading">
			                    <td class="ctg-type">Product</td>
			                    <td class="ctg-type text-center">Unit Price</td>
			                    <td class="ctg-type text-center"><span class="desktop-only">Quantity</span><span class="mobile-only">Qty</span></td>
			                    <td class="ctg-type text-center"><span class="desktop-only">Discount</span><span class="mobile-only">Disc</span></td>
			                    <td class="ctg-type"> Total</td>
			                </tr>
			            </thead>
			            <tbody>
			            <?php
        					if(!empty($order['items']))
        					foreach($order['items'] as $item){
        					?>
        					<tr class="cart_item check-item prd-name">
			                    <td class="ctg-type c-product-img">
			                    	<div class="img-box modified">
			                     		<img src="<?= $item['image']?>" alt="">
					                    <div class="c-product-sku-box">
						                    <span><?= $item['productName']?></span><span class="c-product-sku">(<?= $item['sku']?>)</span>
					                    </div>
				                    	<div class="mobile-only">
						                    <div class="c-product-sku-box">
							                    <span class="c-product-sku-txt">SKU</span>
							                    <span class="c-product-sku"><?= $item['sku']?></span>
						                    </div>
				                     		<span class="c-product-title"><?= $item['productName']?></span>
				                    	</div>
			                    	</div>
			                     </td>
			                    <td class="ctg-type text-center"> <?= $item['currency']. '' .number_format($item['price'], 2) ?> </td>
			                    <td class="ctg-type text-center"> <?= $item['quantity']?>  </td>
			                    <td class="ctg-type text-center"> <?= ($item['discount'])? $item['currency']. '' .number_format($item['discount'], 2) : '' ?>   </td>
			                    <td class="ctg-type"> <?= $item['currency']. '' .number_format($item['total'], 2)?> </td>
			                </tr>
        					<?php 
        					}
    					?>
			            </tbody>
			        </table>
			    </div>
			    <div class="clearfix">
				    <div class="c-order-number-box">
				    	<div class="c-order-number-content">
							<div class="c-order-numbers-row clearfix">
								<div class="c-order-name">
									<span>Subtotal</span>
								</div>
								<div class="c-oder-number">
									<span><?= !empty($order['subTotal'])? $order['currency']. '' .number_format($order['subTotal'], 2) : ''; ?></span>
								</div>
							</div>
							<?php if(!empty($order['coupons'])){ ?>
							<div class="c-order-numbers-row clearfix">
								<div class="c-order-name">
									<span>Discount</span>
								</div>
							</div>
							<div class="c-order-numbers-row clearfix">
								<?php 
								foreach($order['coupons'] as $coupon){
								    
								?>
								<div class="c-order-name">
									<div class="c-order-mini">
										<span>Code: <?= ($coupon['couponCode']) ? '<em>('.$coupon['couponCode'].')</em>' : '' ?></span>
									</div>
								</div>
								<div class="c-oder-number">
									<span><?= !empty($coupon['couponDiscount'])? '-'.$order['currency']. '' .number_format($coupon['couponDiscount'], 2) : $order['currency'].'0'; ?></span>
								</div>
								<?php } ?>
							</div>
							<?php }?>
							<div class="c-order-numbers-row clearfix">
								<div class="c-order-name">
									<span>Shipping</span>
								</div>
								<div class="c-oder-number">
									<span><?= !empty($order['shipping'])? $order['currency']. '' . number_format($order['shipping'], 2): $order['currency'].'0'; ?></span>
								</div>
							</div>
							<div class="c-order-numbers-row clearfix">
								<div class="c-order-name b-total">
									<span>Total</span>
								</div>
								<div class="c-oder-number b-total">
									<span><?= !empty($order['total'])? $order['currency']. '' . number_format($order['total'], 2) : ''; ?></span>
								</div>
							</div>
				    	</div>
				    </div>
			    </div>

			</form>
		</div>
	</div>
</div>
	<br>
	<div class="ship-add">
		<div class="row">
			<div class="col-xs-12 col-md-6">
				<div class="order-address">
					<?= !(empty($this->orderAddressView))? $this->orderAddressView: '' ?>
				</div>
			</div>
			<div class="col-xs-12 col-md-push-1 col-md-4">
				<div class="order-shipping">
					<?= !empty($this->orderShippingDetailsView)? $this->orderShippingDetailsView: '' ?>
				</div>
			</div>
		</div>
	</div>
<?= !(empty($this->orderMessagesView))? $this->orderMessagesView: '' ?>  			
<?php }?>