<div class="add-to-cart-zone">
    <div class="alert alert-danger <?= (!$this->errors) ? 'hidden' : '' ?>">
    	<?php foreach ($this->errors As $err):?>
        	<?php foreach ($err As $subErr):?>
            	<p><?= $subErr?></p>
        	<?php endforeach;?>
    	<?php endforeach;?>
    </div>
    
    <div class="alert alert-success hidden">
    	<p>Product has been added to your cart</p>
    </div>
        
    <div class="add-to-cart-quantity-zone">
        <div class="quantity-area">
            <div class="row">
                <div class="col-xs-5 col-sm-4">
                    <label>Quantity</label>
                </div>
                <div class="col-xs-7 col-sm-8">
                    <div class="cart-quantity">
                    	<?php 
                        	$form = $this->addToCcart;
                        	$form->setAttribute('id', 'add-to-cart-form');
                        	$form->prepare();
                        	echo $this->form()->openTag($form);
                        	echo $this->DemoSiteFieldCollection($form);
                        	echo $this->form()->closeTag();
                    	?>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-7 col-xs-push-5 col-sm-8 col-sm-push-4">
                <a href="#" class="btn-add-cart add-cart add-cart-text" id="add-to-cart" data-pageid="<?= $this->layout()->idPage; ?>" data-bs-placement="left" tabindex="0">Add To Cart<i class="fa fa-cart-plus"></i></a>
            </div>
        </div>
    </div>
</div>