<!--breadcumb area start -->
<?php 
    $subject = $this->MelisTag($this->idPage, 'header_image', 'media', '');
    preg_match('/<img\s.*?\bsrc="(.*?)".*?>/si', $subject, $matches);
    
    $imgSrc = '/MelisDemoCommerce/images/bg/about.jpg';
    if (!empty($matches[1]))
    {
        $imgSrc = $matches[1];
    }
    $imgBg = 'background: rgba(0, 0, 0, 0) url(\''.$imgSrc.'\') no-repeat scroll 0 0';
?>

<div class="breadcumb-area overlay pos-rltv" style="<?php echo $imgBg ?>">
	<?php if ($this->renderMode == 'melis'):?>
    	<div class="breadcumb-area-overlay-media">
    		<?php echo $this->MelisTag($this->idPage, 'header_image', 'media', '<img alt="" src="'.$imgSrc.'">');?>
    	</div>
	<?php endif;?>
    <div class="bread-main">
        <div class="bred-hading text-center">
            <h5><?php echo $this->MelisTag($this->idPage, 'header_title', 'textarea', 'Our Designs')?></h5> 
        </div>
    	<?php echo $this->layout()->pageBreadcrumb?>
    </div>
</div>
<!--breadcumb area end -->

<!-- Account Area Start -->
<div class="account-area ptb-80">
    <div class="container">
        <div class="row">
        	<div class="col-sm-6 col-xs-12">
            	<!-- Login Start -->
                <?php echo $this->login?>
                <!-- End of the Login -->
            </div>
            <div class="col-sm-6 col-xs-12 lr2">
                <!-- Registration Start -->
                <?php echo $this->registration ?>
                <!-- End of Registration -->
            </div>
        </div>
    </div>
</div>
<!-- Account Area End -->