<!--breadcumb area start -->
<?php 
    $imgSrc = (!empty($this->pageBanner)) ? $this->pageBanner : '/MelisDemoCommerce/images/bg/about.jpg';
    $imgBg = 'background: rgba(0, 0, 0, 0) url(\''.$imgSrc.'\') no-repeat scroll 0 0';
?>

<div class="breadcumb-area overlay pos-rltv" style="<?php echo $imgBg ?>">
    <div class="bread-main">
        <div class="bred-hading text-center">
            <h5><?php echo $this->MelisTag($this->idPage, 'header_title', 'textarea', 'Categories')?></h5> 
        </div>
        <?php echo $this->layout()->pageBreadcrumb?>
    </div>
</div>
<!--breadcumb area end -->

<!--shop main area are start-->
<div class="shop-main-area ptb-70">
    <div class="container">
        <div class="row">
            <!--shop sidebar start-->
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="row">
                    <div class="shop-sidebar">
                       <!--single aside start-->
                        <aside class="single-aside search-aside search-box">
                            <form action="#" id="catalogueSearchForm">
                                <div class="input-box">
                                <?php $searchValue = !empty($this->layout()->queryParameters['m_box_filter_search'])? $this->layout()->queryParameters['m_box_filter_search'] : ''; ?>
                                    <input name="m_box_filter_search" class="single-input" placeholder="Search...." type="text" value="<?= $searchValue ?>">
                                    <button id="catalogueSearch" class="src-btn sb-2"><i class="fa fa-search"></i></button>
                                </div>
                            </form>
                         </aside>
                        <!--single aside end-->
                        
                        <!--single aside start-->
                        <?php echo $this->categoryListFilter ?>
                        <!--single aside end-->
                        
                        <!--single aside start-->
                        <?php echo $this->priceFilter ?>
                        <!--single aside end-->
                        
                        <!--single aside start-->
                        <?php echo $this->colorAttributeFilter ?>
                        <!--single aside end-->
                        
                        <!--single aside start-->
                        <?php echo $this->sizeAttributeFilter ?>
                        <!--single aside end-->
                        
                        <!--single aside start-->
                        <!--  
                        <aside class="single-aside tag-aside">
                            <div class="heading-title aside-title pos-rltv">
                                <h5 class="uppercase">Product Tags</h5> 
                            </div>
                            <ul class="tag-filter mt-30">
                                <li><a href="#">Fashion</a></li>
                                <li><a href="#">Women</a></li>
                                <li><a href="#">Winter</a></li>
                                <li><a href="#">Street Style</a></li>
                                <li><a href="#">Style</a></li>
                                <li><a href="#">Shop</a></li>
                                <li><a href="#">Collection</a></li>
                                <li><a href="#">Spring 2016</a></li>
                            </ul>
                        </aside>
                        -->
                        <!--single aside end-->
                        
                        <!--single aside start-->
                        <aside class="single-aside tag-aside">
                            <button class="btn btn-danger btn-block" id="catalogueFilter">Filter</button>
                        </aside>
                        <!--single aside end-->
                        
                    </div>
                </div>
            </div>
            <!--shop sidebar end-->
            
            <!--main-shop-product start-->
        	<?php echo $this->categoryProductList ?>
            <!--main-shop-product end-->
        </div>
    </div>
</div>
<!--shop main area are end-->