<div class="row">
    <div class="col-xs-12 best-heading text-center">
        <h3>Best Product Collection</h3>
        <div class="best-text">
            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum. It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum.</p>
        </div>
        <a class="view-all" href="">View all</a>
    </div>
</div>