<div class="row">
    <div class="col-md-8 col-sm-12 col-xs-12">
        <div class="banner-area-left ">
           <div class="banner-single pos-rltv fix mb-30">
                <div class="banner-img"> 
                    <img src="/MelisDemoCommerce/images/product/banner-01.jpg" alt="" onerror="this.onerror=null;this.src='/MelisDemoCms/images/image-not-found.png';"> 
                </div>
                <div class="banner-content">
                    <div class="heading-title big-title heading-style pos-rltv">
                        <h3 class=""><a href="#">Best Collection For Men</a></h3> 
                    </div>
                    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </p> <a href="#" class="btn-def" tabindex="0">Shop Now</a> 
                </div>
           </div>
           <div class="banner-single pos-rltv fix">
                <div class="banner-img left-type"> 
                    <img src="/MelisDemoCommerce/images/product/banner-02.jpg" alt="" onerror="this.onerror=null;this.src='/MelisDemoCms/images/image-not-found.png';"> 
                </div>
                <div class="banner-content left-type">
                    <div class="heading-title big-title heading-style pos-rltv">
                        <h3 class=""><a href="#">Women's Fashion</a></h3> 
                    </div>
                    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </p> <a href="#" class="btn-def" tabindex="0">Shop Now</a> 
                </div>
           </div>
        </div>
    </div>
    <div class="col-md-4 hidden-sm col-xs-12">
        <div class="banner-img-2 pos-rltv"> <img src="/MelisDemoCommerce/images/product/banner-03.jpg" alt="" onerror="this.onerror=null;this.src='/MelisDemoCms/images/image-not-found.png';">
            <div class="banner-timer shadow-box-2">
                <div class="timer-wraper text-center">
                    <div class="timer timr-2">
                        <div data-countdown="2015/02/01"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="banner-content-2 mt-25">
            <div class="heading-title big-title">
                <h3 class=""><a href="#">Luxary Products</a></h3> 
            </div>
            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </p>
            <a href="#" class="btn-def" tabindex="0">Order Now</a>
        </div>
    </div>
</div>