<div class="instagrm">
    <ul>
        <li><a href="#"><img src="/MelisDemoCommerce/images/gallery/01.jpg" alt=""></a></li>
        <li><a href="#"><img src="/MelisDemoCommerce/images/gallery/02.jpg" alt=""></a></li>
        <li><a href="#"><img src="/MelisDemoCommerce/images/gallery/03.jpg" alt=""></a></li>
        <li><a href="#"><img src="/MelisDemoCommerce/images/gallery/04.jpg" alt=""></a></li>
        <li><a href="#"><img src="/MelisDemoCommerce/images/gallery/05.jpg" alt=""></a></li>
        <li><a href="#"><img src="/MelisDemoCommerce/images/gallery/06.jpg" alt=""></a></li>
    </ul>
</div>
