<!--breadcumb area start -->
<?php
    $subject = $this->MelisTag($this->idPage, 'header_image', 'media', '');
    preg_match('/<img\s.*?\bsrc="(.*?)".*?>/si', $subject, $matches);
    
    $imgSrc = '/MelisDemoCommerce/images/bg/about.jpg';
    if (!empty($matches[1]))
    {
        $imgSrc = $matches[1];
    }
    $imgBg = 'background: rgba(0, 0, 0, 0) url(\''.$imgSrc.'\') no-repeat scroll 0 0';
?>

<div class="breadcumb-area overlay pos-rltv" style="<?php echo $imgBg ?>">
    <?php if ($this->renderMode == 'melis'):?>
        <div class="breadcumb-area-overlay-media">
            <?php echo $this->MelisTag($this->idPage, 'header_image', 'media', '<img alt="" src="'.$imgSrc.'">');?>
        </div>
    <?php endif;?>
    <div class="bread-main">
        <div class="bred-hading text-center">
            <h5><?php echo $this->MelisTag($this->idPage, 'header_title', 'textarea', 'Our Designs')?></h5> 
        </div>
        <?php echo $this->layout()->pageBreadcrumb?>
    </div>
</div>
<!--breadcumb area end -->
<?php echo $this->lostPassword_lostPasswordReset?>

<!-- Account Area Start -->
<!--  
<div class="account-area ptb-80">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-push-3 col-xs-12">
                <form action="#" class="login-side">
                    <div class="login-reg reset-pass">
                        <h3>Choose a new password</h3>
                        <div class="input-box mb-15">
                            <label class="control-label"><input type="password" placeholder="Password" value="" name="password" class="info"></label>
                        </div>
                        <div class="input-box mb-15">
                            <label class="control-label"><input type="password" placeholder="Password2" value="" name="password2" class="info"></label>
                        </div>
                        <div class="input-box mb-15">
                            <button type="submit" class="btn-def btn2 fw">Reset!</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
-->
<!-- Account Area End -->


