<?php
    return array(
        array(
            'columns' => array(
                'cli_status' => 1,
                'cli_country_id' => 1,
            ),
            'client_persons' => array(
                array(
                    'columns' => array(
                        'cper_lang_id' => 1,
                        'cper_status' => 1,
                        'cper_is_main_person' => 1,
                        'cper_email' => 'demo@melisplatform.com',
                        'cper_password' => 'demo2017',
                        'cper_civility' => 1,
                        'cper_name' => 'DOE',
                        'cper_firstname' => 'John',
                    ),
                    'client_person_addresses' => array(
                        array(
                            'cadd_type' => 2,
                            'cadd_address_name' => 'Home',
                            'cadd_civility' => 1,
                            'cadd_name' => 'DOE',
                            'cadd_middle_name' => '',
                            'cadd_firstname' => 'John',
                            'cadd_num' => 4,
                            'cadd_stairs' => '',
                            'cadd_building_name' => '',
                            'cadd_company' => '',
                            'cadd_street' => 'rue du Dahomey',
                            'cadd_zipcode' => '75011',
                            'cadd_city' => 'Paris',
                            'cadd_state' => '',
                            'cadd_country' => '',
                            'cadd_complementary' => '',
                            'cadd_phone_mobile' => '',
                            'cadd_phone_landline' => '0972386280',
                        ),
                    ),
                    'client_person_orders' => array(
                        array(
                            'order' => array(
                                'ord_status' => 4,
                                'ord_country_id' => 1,
                                'ord_reference' => 'I06DKJW7YE',
                            ),
                            'order_baskets' => array(
                                array(
                                    'obas_order_id' => 1,
                                    'obas_variant_id' => 'Duvo03',
                                    'obas_product_name' => 'Duvo',
                                    'obas_quantity' => 1,
                                    'obas_sent' => 0,
                                    'obas_sku' => 'Duvo03',
                                    'obas_attributes' => 'Blue, L, Cotton',
                                    'obas_category_name' => 'Trendy',
                                    'obas_currency' => 2,
                                    'obas_price_net' => 57,
                                ),
                                array(
                                    'obas_order_id' => 1,
                                    'obas_variant_id' => 'Bendo01',
                                    'obas_product_name' => 'Bendo',
                                    'obas_quantity' => 2,
                                    'obas_sent' => 0,
                                    'obas_sku' => 'Bendo01',
                                    'obas_attributes' => 'Cotton, Black, Male',
                                    'obas_category_name' => 'Hats',
                                    'obas_currency' => 2,
                                    'obas_price_net' => 65,
                                ),
                                array(
                                    'obas_order_id' => 1,
                                    'obas_variant_id' => 'Zekker07',
                                    'obas_product_name' => 'Zekker',
                                    'obas_quantity' => 1,
                                    'obas_sent' => 0,
                                    'obas_sku' => 'Zekker07',
                                    'obas_attributes' => 'Brown, 45',
                                    'obas_category_name' => 'Classy',
                                    'obas_currency' => 2,
                                    'obas_price_net' => 95,
                                ),
                            ),
                            'order_addresses' => array(
                                array(
                                    'oadd_type' => 1,
                                    'oadd_civility' => 1,
                                    'oadd_name' => 'DOE',
                                    'oadd_middle_name' => '',
                                    'oadd_firstname' => 'John',
                                    'oadd_num' => 4,
                                    'oadd_stairs' => '',
                                    'oadd_building_name' => '',
                                    'oadd_company' => '',
                                    'oadd_street' => 'rue du Dahomey',
                                    'oadd_zipcode' => '75011',
                                    'oadd_city' => 'Paris',
                                    'oadd_state' => '',
                                    'oadd_country' => '',
                                    'oadd_complementary' => '',
                                    'oadd_phone_mobile' => '',
                                    'oadd_phone_landline' => '0972386280',
                                ),
                                array(
                                    'oadd_type' => 2,
                                    'oadd_civility' => 1,
                                    'oadd_name' => 'DOE',
                                    'oadd_middle_name' => '',
                                    'oadd_firstname' => 'John',
                                    'oadd_num' => 4,
                                    'oadd_stairs' => '',
                                    'oadd_building_name' => '',
                                    'oadd_company' => '',
                                    'oadd_street' => 'rue du Dahomey',
                                    'oadd_zipcode' => '75011',
                                    'oadd_city' => 'Paris',
                                    'oadd_state' => '',
                                    'oadd_country' => '',
                                    'oadd_complementary' => '',
                                    'oadd_phone_mobile' => '',
                                    'oadd_phone_landline' => '0972386280',
                                ),
                            ),
                            'order_coupon' => array(
                            ),
                            'order_payment' => array(
                                array(
                                    'opay_id' => 1,
                                    'opay_order_id' => 1,
                                    'opay_price_total' => 382,
                                    'opay_price_order' => 282,
                                    'opay_price_shipping' => 100,
                                    'opay_currency_id' => -1,
                                    'opay_payment_type_id' => 1,
                                    'opay_transac_id' => '35A1CZRURS',
                                    'opay_transac_return_value' => 'A',
                                    'opay_transac_price_paid_confirm' => 382,
                                    'opay_transac_raw_response' => '{"payment-transaction-price-paid":"382","payment-transaction-price-paid-confirm":"382","payment-type-value":"VISA","payment-transaction-id":"35A1CZRURS","payment-transaction-return-code":"A","payment-transaction-date":"2017-04-06 08:20:37","order-id":"1","payment-transaction-total-cost":"382","checkout-confirm-url":"http:\/\/melisdemoecommerce.melis2.melistechnology.fr\/checkout\/id\/20?m_checkout_step=checkout-confirm&m_order_id=1"}',
                                    'opay_date_payment' => '2017-04-06 08:20:38',
                                ),
                            ),
                            'order_shipping' => array(
                            ),
                        ),
                        array(
                            'order' => array(
                                'ord_status' => 3,
                                'ord_country_id' => 1,
                                'ord_reference' => '3LUSO3M4CP',
                            ),
                            'order_baskets' => array(
                                array(
                                    'obas_order_id' => 2,
                                    'obas_variant_id' => 'Valena02',
                                    'obas_product_name' => 'Valena',
                                    'obas_quantity' => 1,
                                    'obas_sent' => 0,
                                    'obas_sku' => 'Valena02',
                                    'obas_attributes' => 'Red, M, Cotton',
                                    'obas_category_name' => 'Flashy',
                                    'obas_currency' => 2,
                                    'obas_price_net' => 26,
                                ),
                                array(
                                    'obas_order_id' => 2,
                                    'obas_variant_id' => 'Blint01',
                                    'obas_product_name' => 'Blint',
                                    'obas_quantity' => 1,
                                    'obas_sent' => 0,
                                    'obas_sku' => 'Blint01',
                                    'obas_attributes' => 'Blue, Male',
                                    'obas_category_name' => 'Best seller',
                                    'obas_currency' => 2,
                                    'obas_price_net' => 225,
                                ),
                            ),
                            'order_addresses' => array(
                                array(
                                    'oadd_type' => 1,
                                    'oadd_civility' => 1,
                                    'oadd_name' => 'DOE',
                                    'oadd_middle_name' => '',
                                    'oadd_firstname' => 'John',
                                    'oadd_num' => 4,
                                    'oadd_stairs' => '',
                                    'oadd_building_name' => '',
                                    'oadd_company' => '',
                                    'oadd_street' => 'rue du Dahomey',
                                    'oadd_zipcode' => '75011',
                                    'oadd_city' => 'Paris',
                                    'oadd_state' => '',
                                    'oadd_country' => '',
                                    'oadd_complementary' => '',
                                    'oadd_phone_mobile' => '',
                                    'oadd_phone_landline' => '0972386280',
                                ),
                                array(
                                    'oadd_type' => 2,
                                    'oadd_civility' => 1,
                                    'oadd_name' => 'DOE',
                                    'oadd_middle_name' => '',
                                    'oadd_firstname' => 'John',
                                    'oadd_num' => 4,
                                    'oadd_stairs' => '',
                                    'oadd_building_name' => '',
                                    'oadd_company' => '',
                                    'oadd_street' => 'rue du Dahomey',
                                    'oadd_zipcode' => '75011',
                                    'oadd_city' => 'Paris',
                                    'oadd_state' => '',
                                    'oadd_country' => '',
                                    'oadd_complementary' => '',
                                    'oadd_phone_mobile' => '',
                                    'oadd_phone_landline' => '0972386280',
                                ),
                            ),
                            'order_coupon' => array(
                            ),
                            'order_payment' => array(
                                array(
                                    'opay_id' => 2,
                                    'opay_order_id' => 2,
                                    'opay_price_total' => 351,
                                    'opay_price_order' => 251,
                                    'opay_price_shipping' => 100,
                                    'opay_currency_id' => -1,
                                    'opay_payment_type_id' => 1,
                                    'opay_transac_id' => 'FSFNI6F8NS',
                                    'opay_transac_return_value' => 'A',
                                    'opay_transac_price_paid_confirm' => 351,
                                    'opay_transac_raw_response' => '{"payment-transaction-price-paid":"351","payment-transaction-price-paid-confirm":"351","payment-type-value":"VISA","payment-transaction-id":"FSFNI6F8NS","payment-transaction-return-code":"A","payment-transaction-date":"2017-04-06 08:57:45","order-id":"2","payment-transaction-total-cost":"351","checkout-confirm-url":"http:\/\/melisdemoecommerce.melis2.melistechnology.fr\/checkout\/id\/20?m_checkout_step=checkout-confirm&m_order_id=2"}',
                                    'opay_date_payment' => '2017-04-06 08:57:47',
                                ),
                            ),
                            'order_shipping' => array(
                            ),
                        ),
                        array(
                            'order' => array(
                                'ord_status' => 1,
                                'ord_country_id' => 1,
                                'ord_reference' => 'B9OOR6SZ6V',
                            ),
                            'order_baskets' => array(
                                array(
                                    'obas_order_id' => 3,
                                    'obas_variant_id' => 'Lano01',
                                    'obas_product_name' => 'Lano',
                                    'obas_quantity' => 1,
                                    'obas_sent' => 0,
                                    'obas_sku' => 'Lano01',
                                    'obas_attributes' => '',
                                    'obas_category_name' => 'Silver pure',
                                    'obas_currency' => 2,
                                    'obas_price_net' => 320,
                                ),
                                array(
                                    'obas_order_id' => 3,
                                    'obas_variant_id' => 'Epalas01',
                                    'obas_product_name' => 'Epalas',
                                    'obas_quantity' => 1,
                                    'obas_sent' => 0,
                                    'obas_sku' => 'Epalas01',
                                    'obas_attributes' => 'Grey, S, Nylon',
                                    'obas_category_name' => 'Treasure',
                                    'obas_currency' => 2,
                                    'obas_price_net' => 32,
                                ),
                                array(
                                    'obas_order_id' => 3,
                                    'obas_variant_id' => 'Klate04',
                                    'obas_product_name' => 'Klate',
                                    'obas_quantity' => 1,
                                    'obas_sent' => 0,
                                    'obas_sku' => 'Klate04',
                                    'obas_attributes' => 'Black, 38',
                                    'obas_category_name' => 'Boots',
                                    'obas_currency' => 2,
                                    'obas_price_net' => 156,
                                ),
                                array(
                                    'obas_order_id' => 3,
                                    'obas_variant_id' => 'Jophie01',
                                    'obas_product_name' => 'Jophie',
                                    'obas_quantity' => 1,
                                    'obas_sent' => 0,
                                    'obas_sku' => 'Jophie01',
                                    'obas_attributes' => 'Female, Red, Nylon',
                                    'obas_category_name' => 'Best seller',
                                    'obas_currency' => 2,
                                    'obas_price_net' => 145,
                                ),
                            ),
                            'order_addresses' => array(
                                array(
                                    'oadd_type' => 1,
                                    'oadd_civility' => 1,
                                    'oadd_name' => 'DOE',
                                    'oadd_middle_name' => '',
                                    'oadd_firstname' => 'John',
                                    'oadd_num' => 4,
                                    'oadd_stairs' => '',
                                    'oadd_building_name' => '',
                                    'oadd_company' => '',
                                    'oadd_street' => 'rue du Dahomey',
                                    'oadd_zipcode' => '75011',
                                    'oadd_city' => 'Paris',
                                    'oadd_state' => '',
                                    'oadd_country' => '',
                                    'oadd_complementary' => '',
                                    'oadd_phone_mobile' => '',
                                    'oadd_phone_landline' => '0972386280',
                                ),
                                array(
                                    'oadd_type' => 2,
                                    'oadd_civility' => 1,
                                    'oadd_name' => 'DOE',
                                    'oadd_middle_name' => '',
                                    'oadd_firstname' => 'John',
                                    'oadd_num' => 4,
                                    'oadd_stairs' => '',
                                    'oadd_building_name' => '',
                                    'oadd_company' => '',
                                    'oadd_street' => 'rue du Dahomey',
                                    'oadd_zipcode' => '75011',
                                    'oadd_city' => 'Paris',
                                    'oadd_state' => '',
                                    'oadd_country' => '',
                                    'oadd_complementary' => '',
                                    'oadd_phone_mobile' => '',
                                    'oadd_phone_landline' => '0972386280',
                                ),
                            ),
                            'order_coupon' => array(
                                'cord_coupon_id' => '10DISCOUNT',
                                'cord_quantity_used' => 1
                            ),
                            'order_payment' => array(
                                array(
                                    'opay_id' => 3,
                                    'opay_order_id' => 3,
                                    'opay_price_total' => 687.7,
                                    'opay_price_order' => 653,
                                    'opay_price_shipping' => 100,
                                    'opay_currency_id' => -1,
                                    'opay_payment_type_id' => 1,
                                    'opay_transac_id' => 'Y634ZEPWN0',
                                    'opay_transac_return_value' => 'A',
                                    'opay_transac_price_paid_confirm' => 687.7,
                                    'opay_transac_raw_response' => '{"payment-transaction-price-paid":"687.7","payment-transaction-price-paid-confirm":"687.7","payment-type-value":"VISA","payment-transaction-id":"Y634ZEPWN0","payment-transaction-return-code":"A","payment-transaction-date":"2017-04-06 11:41:36","order-id":"3","payment-transaction-total-cost":"687.7","checkout-confirm-url":"http:\/\/melisdemoecommerce.melis2.melistechnology.fr\/checkout\/id\/20?m_checkout_step=checkout-confirm&m_order_id=3"}',
                                    'opay_date_payment' => '2017-04-06 11:41:36',
                                ),
                            ),
                            'order_shipping' => array(
                            ),
                        ),
                        array(
                            'order' => array(
                                'ord_status' => 1,
                                'ord_country_id' => 1,
                                'ord_reference' => 'MLLV30XW72',
                            ),
                            'order_baskets' => array(
                                array(
                                    'obas_order_id' => 4,
                                    'obas_variant_id' => 'Jader04',
                                    'obas_product_name' => 'Jader',
                                    'obas_quantity' => 1,
                                    'obas_sent' => 0,
                                    'obas_sku' => 'Jader04',
                                    'obas_attributes' => 'Black, XL, Leather',
                                    'obas_category_name' => 'Styled',
                                    'obas_currency' => 2,
                                    'obas_price_net' => 68,
                                ),
                                array(
                                    'obas_order_id' => 4,
                                    'obas_variant_id' => 'Peleo03',
                                    'obas_product_name' => 'Peleo',
                                    'obas_quantity' => 1,
                                    'obas_sent' => 0,
                                    'obas_sku' => 'Peleo03',
                                    'obas_attributes' => 'Blue, L, Cotton',
                                    'obas_category_name' => 'Classy',
                                    'obas_currency' => 2,
                                    'obas_price_net' => 184,
                                ),
                                array(
                                    'obas_order_id' => 4,
                                    'obas_variant_id' => 'Mentor01',
                                    'obas_product_name' => 'Mentor',
                                    'obas_quantity' => 1,
                                    'obas_sent' => 0,
                                    'obas_sku' => 'Mentor01',
                                    'obas_attributes' => 'Brown, Male',
                                    'obas_category_name' => 'Watches',
                                    'obas_currency' => 2,
                                    'obas_price_net' => 280,
                                ),
                            ),
                            'order_addresses' => array(
                                array(
                                    'oadd_type' => 1,
                                    'oadd_civility' => 1,
                                    'oadd_name' => 'DOE',
                                    'oadd_middle_name' => '',
                                    'oadd_firstname' => 'John',
                                    'oadd_num' => 4,
                                    'oadd_stairs' => '',
                                    'oadd_building_name' => '',
                                    'oadd_company' => '',
                                    'oadd_street' => 'rue du Dahomey',
                                    'oadd_zipcode' => '75011',
                                    'oadd_city' => 'Paris',
                                    'oadd_state' => '',
                                    'oadd_country' => '',
                                    'oadd_complementary' => '',
                                    'oadd_phone_mobile' => '',
                                    'oadd_phone_landline' => '0972386280',
                                ),
                                array(
                                    'oadd_type' => 2,
                                    'oadd_civility' => 1,
                                    'oadd_name' => 'DOE',
                                    'oadd_middle_name' => '',
                                    'oadd_firstname' => 'John',
                                    'oadd_num' => 4,
                                    'oadd_stairs' => '',
                                    'oadd_building_name' => '',
                                    'oadd_company' => '',
                                    'oadd_street' => 'rue du Dahomey',
                                    'oadd_zipcode' => '75011',
                                    'oadd_city' => 'Paris',
                                    'oadd_state' => '',
                                    'oadd_country' => '',
                                    'oadd_complementary' => '',
                                    'oadd_phone_mobile' => '',
                                    'oadd_phone_landline' => '0972386280',
                                ),
                            ),
                            'order_coupon' => array(
                            ),
                            'order_payment' => array(
                                array(
                                    'opay_id' => 4,
                                    'opay_order_id' => 4,
                                    'opay_price_total' => 632,
                                    'opay_price_order' => 532,
                                    'opay_price_shipping' => 100,
                                    'opay_currency_id' => -1,
                                    'opay_payment_type_id' => 1,
                                    'opay_transac_id' => 'U6LQBGCHBA',
                                    'opay_transac_return_value' => 'A',
                                    'opay_transac_price_paid_confirm' => 632,
                                    'opay_transac_raw_response' => '{"payment-transaction-price-paid":"632","payment-transaction-price-paid-confirm":"632","payment-type-value":"VISA","payment-transaction-id":"U6LQBGCHBA","payment-transaction-return-code":"A","payment-transaction-date":"2017-04-06 11:55:47","order-id":"4","payment-transaction-total-cost":"632","checkout-confirm-url":"http:\/\/melisdemoecommerce.melis2.melistechnology.fr\/checkout\/id\/20?m_checkout_step=checkout-confirm&m_order_id=4"}',
                                    'opay_date_payment' => '2017-04-06 11:55:48',
                                ),
                            ),
                            'order_shipping' => array(
                            ),
                        ),
                    ),
                )
            ),
        ),
    );