<?php
    return array(
        array(
            'tpl_name' => 'Home',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'Home',
            'tpl_zf2_action' => 'index',
        ),
        array(
            'tpl_name' => 'Commerce Catalogue',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'ComCatalogue',
            'tpl_zf2_action' => 'index',
        ),
        array(
            'tpl_name' => 'News List',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'News',
            'tpl_zf2_action' => 'list',
        ),
        array(
            'tpl_name' => 'News Details',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'News',
            'tpl_zf2_action' => 'details',
        ),
        array(
            'tpl_name' => 'About Us',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'About',
            'tpl_zf2_action' => 'aboutus',
        ),
        array(
            'tpl_name' => 'Contact Us',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'Contact',
            'tpl_zf2_action' => 'contactus',
        ),
        array(
            'tpl_name' => 'Testimonial',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'Testimonial',
            'tpl_zf2_action' => 'testimonial',
        ),
        array(
            'tpl_name' => 'Commerce Product',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'ComProduct',
            'tpl_zf2_action' => 'index',
        ),
        array(
            'tpl_name' => 'Commerce Checkout',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'ComCheckout',
            'tpl_zf2_action' => 'checkout',
        ),
        array(
            'tpl_name' => 'Commerce Login',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'ComLogin',
            'tpl_zf2_action' => 'index',
        ),
        array(
            'tpl_name' => 'Commerce Lost Password',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'ComLostPassword',
            'tpl_zf2_action' => 'index',
        ),
        array(
            'tpl_name' => 'Search Results',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'Search',
            'tpl_zf2_action' => 'results',
        ),
        array(
            'tpl_name' => 'Commerce My Account',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'ComMyAccount',
            'tpl_zf2_action' => 'index',
        ),
        array(
            'tpl_name' => 'Order details',
            'tpl_type' => 'ZF2',
            'tpl_zf2_website_folder'=> 'MelisDemoCommerce',
            'tpl_zf2_layout' => 'defaultLayout',
            'tpl_zf2_controller' => 'ComOrder',
            'tpl_zf2_action' => 'index',
        )
    );