<?php
    return array(
        array(
            'site_config' => 'colorAttributeId',
            'columns' => array(
                'attr_type_id' => 'Text',
                'attr_status' => 1,
                'attr_reference' => 'Color',
                'attr_visible' => 1,
                'attr_searchable' => 1,
            ),
            'attribute_trans' => array(
                array(
                    'atrans_lang_id' => 1,
                    'atrans_name' => 'Color',
                    'atrans_description' => '',
                ),
            ),
            'attribute_values' => array(
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Black',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Black',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'White',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'White',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Red',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Red',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Blue',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Blue',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Green',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Green',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Purple',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Purple',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Orange',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Orange',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Yellow',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Yellow',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Grey',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Grey',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Brown',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Brown',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Pink',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Pink',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
            ),
        ),
        array(
            'site_config' => 'sizeAttributeId',
            'columns' => array(
                'attr_type_id' => 'Text',
                'attr_status' => 1,
                'attr_reference' => 'Size',
                'attr_visible' => 1,
                'attr_searchable' => 1,
            ),
            'attribute_trans' => array(
                array(
                    'atrans_lang_id' => 1,
                    'atrans_name' => 'Size',
                    'atrans_description' => '',
                ),
            ),
            'attribute_values' => array(
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'S',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'S',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'M',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'M',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'L',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'L',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'XL',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'XL',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'XXL',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'XXL',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
            ),
        ),
        array(
            'columns' => array(
                'attr_type_id' => 'Text',
                'attr_status' => 1,
                'attr_reference' => 'Texture',
                'attr_visible' => 1,
                'attr_searchable' => 1,
            ),
            'attribute_trans' => array(
                array(
                    'atrans_lang_id' => 1,
                    'atrans_name' => 'Texture',
                    'atrans_description' => '',
                ),
            ),
            'attribute_values' => array(
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Cotton',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Cotton',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Silk',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Silk',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Nylon',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Nylon',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Wool',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Wool',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Text',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Leather',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => 'Leather',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
            ),
        ),
        array(
            'columns' => array(
                'attr_type_id' => 'Short string',
                'attr_status' => 1,
                'attr_reference' => 'Gender',
                'attr_visible' => 1,
                'attr_searchable' => 1,
            ),
            'attribute_trans' => array(
                array(
                    'atrans_lang_id' => 1,
                    'atrans_name' => 'Gender',
                    'atrans_description' => '',
                ),
            ),
            'attribute_values' => array(
                array(
                    'columns' => array(
                        'atval_type_id' => 'Short string',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => 'Male',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => 'Male',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Short string',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => 'Female',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => '',
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => 'Female',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
            ),
        ),
        array(
            'columns' => array(
                'attr_type_id' => 'Integer',
                'attr_status' => 1,
                'attr_reference' => 'Shoe size',
                'attr_visible' => 1,
                'attr_searchable' => 1,
            ),
            'attribute_trans' => array(
                array(
                    'atrans_lang_id' => 1,
                    'atrans_name' => 'Shoe size',
                    'atrans_description' => '',
                ),
            ),
            'attribute_values' => array(
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 35,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 35,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 36,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 36,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 37,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 37,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 38,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 38,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 39,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 39,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 40,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 40,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 41,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 41,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 42,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 42,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 43,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 43,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 44,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 44,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 45,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 45,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 46,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 46,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
                array(
                    'columns' => array(
                        'atval_type_id' => 'Integer',
                        'atval_reference' => '',
                    ),
                    'attribute_value_trans' => array(
                        array(
                            'avt_lang_id' => 1,
                            'avt_v_int' => 47,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                        array(
                            'avt_lang_id' => 2,
                            'avt_v_int' => 47,
                            'avt_v_float' => '',
                            'avt_v_bool' => '',
                            'avt_v_varchar' => '',
                            'avt_v_text' => '',
                            'avt_v_datetime' => '',
                            'avt_v_binary' => '',
                        ),
                    ),
                ),
            ),
        ),
    );