<!doctype html>
<html class="no-js" lang="en">

<head>
<title></title>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php 
        /* All css files are included here. */
        
        // Favicon
        $this->headLink(array('rel' => 'apple-touch-icon', 'href' => $this->basePath('/MelisDemoCommerce/images/icons/favicon.ico'), 'PREPEND'));
        
        // Render Page CSS from Controller Action of the page
        if (is_array($this->pageCss)){
            for ($i = 0 ; $i < count($this->pageCss); $i++){
                $this->headLink()->appendStylesheet($this->pageCss[$i]);
            }
        }
        
        // Generate Styles
        echo $this->headLink();
        
        // Modernizr JS
        $this->headScript()->appendFile($this->basePath('/MelisDemoCommerce/js/vendor/modernizr-2.8.3.min.js'));
        
        // Generate JS
        echo $this->headScript();
    ?>
</head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->  
        
        <!-- Body main wrapper start -->
        <div class="wrapper home-one">
            <!-- Start of header area -->
            <header class="header-area header-wrapper">
                <div class="header-top-bar black-bg clearfix">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-3 col-sm-3 col-xs-6">
                                <div class="login-register-area">
                                    <ul>
                                        <?php if ($this->layout()->isLoggedin):?>
                                            <li><a href="<?php echo $this->MelisLink($this->SiteConfig('account_page_id'), true)?>" id="person-name"><?php echo ucwords(strtolower($this->layout()->personName)) ?></a></li>
                                            <li><a href="/MelisDemoCommerce/ComLogout/logout?pageId=<?= $this->idPage; ?>">Logout</a></li>
                                        <?php else:?>
                                            <li><a href="<?php echo $this->MelisLink($this->SiteConfig('login_regestration_page_id'), true)?>">Login</a></li>
                                            <li><a href="<?php echo $this->MelisLink($this->SiteConfig('login_regestration_page_id'), true)?>">Register</a></li>
                                        <?php endif;?>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-6 hidden-xs">
                                <div class="social-search-area text-center">
                                    <div class="social-icon socile-icon-style-2">
                                        <ul>
                                            <li><a href="https://www.facebook.com/melistechnology" title="facebook" target="_blank"><i class="fa fa-facebook"></i></a> </li>
                                            <li><a href="https://twitter.com/meliscms" title="twitter" target="_blank"><i class="fa fa-twitter"></i></a> </li>
                                            <li><a href="https://www.linkedin.com/company/melis-technology" title="linkedin" target="_blank"><i class="fa fa-linkedin"></i></a> </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-6">
                                <div class="cart-currency-area login-register-area text-right">
                                    <ul>
                                        <li>
                                            <div class="header-cart">
                                            <?php echo $this->menuCart ?>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="sticky-header"  class="header-middle-area">
                    <div class="container">
                        <div class="full-width-mega-dropdown">
                            <div class="row">
                                <div class="col-md-2 col-sm-2">
                                    <div class="logo ptb-20"><a href="/"> 
                                    <img src="<?php echo $this->basePath('/MelisDemoCommerce/images/logo/logo.png')?>" alt="main logo"></a>
                                    </div>
                                </div>
                                <div class="col-md-10 col-sm-10 col-xs-12 m-no-padding">
                                <!-- Site Menu -->
                                <?php echo $this->layout()->siteMenu ?>
                                <!-- End of Site Menu -->
                                </div>
                                <!-- Header Search Menu -->
                                <!-- <div class="col-md-2 hidden-sm hidden-xs">
                                    <div class="search-box global-table">
                                        <div class="global-row">
                                            <div class="global-cell">
                                                <form action="<?php echo $this->MelisLink($this->SiteConfig('search_result_page_id'), false)?>" method="get">
                                                    <div class="input-box">
                                                        <input class="single-input" placeholder="Search" type="text" name="keyword" value="<?php echo $this->layout()->search?>" required>
                                                        <button class="src-btn"><i class="fa fa-search"></i></button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div> -->
                                <!-- End of Header Search Menu -->
                                
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- End of header area -->
            
            <?php echo $this->MelisDragDropZone($this->idPage, "dragdropzone_1") ?>
            <?php echo $this->MelisDragDropZone($this->idPage, "dragdropzone_2") ?>
            
            <!-- Content area start -->
            <?php echo $this->content?>
            <!-- End of Content area -->
            
            <?php 
                /*
                * Layout footer can only edit/modified on Main Page of the Site or the Homepage of the site
                * */
            ?>
            <!-- footer area start-->
            <div class="footer-area ptb-50">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                            <div class="single-footer contact-us">
                                <div class="footer-title uppercase">
                                    <h5>
                                    <?php echo $this->MelisTag($this->SiteConfig('homePageId'), "footer_title_1", 'textarea', 'Contact US') ?>
                                </h5> 
                                </div>
                                <?php 
                                    echo $this->MelisTag($this->SiteConfig('homePageId'), 'footer_text_1', 'html',
                                    '<ul>
                                        <li>
                                            <div class="contact-icon"> 
                                            <i class="zmdi zmdi-pin-drop"></i>
                                        </div>
                                            <div class="contact-text">
                                                <p><span>777/a  Seventh Street,</span> <span>Rampura, Bonosri</span></p>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="contact-icon"> <i class="zmdi zmdi-email-open"></i> </div>
                                            <div class="contact-text">
                                                <p><span><a href="#">company@gmail.com</a></span> <span><a href="#">admin@devitems.com</a></span></p>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="contact-icon"> <i class="zmdi zmdi-phone-paused"></i> </div>
                                            <div class="contact-text">
                                                <p><span>+11 (019) 25184203</span> <span>+11 (018) 50950555</span></p>
                                            </div>
                                        </li>
                                    </ul>')
                                ?>
                            </div>
                        </div>
                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-12">
                            <div class="single-footer informaton-area">
                                <div class="footer-title uppercase">
                                    <h5><?php echo $this->MelisTag($this->SiteConfig('homePageId'), "footer_title_2", 'textarea', 'Information')?></h5>
                                </div>
                                <div class="informatoin">
                                    <ul>
                                    <?php 
                                            echo $this->MelisTag($this->SiteConfig('homePageId'), 'footer_text_2', 'html',
                                                '<li><a href="#">My Account</a></li>
                                                <li><a href="#">Order History</a></li>
                                                <li><a href="#">Wishlist</a></li>
                                                <li><a href="#">Returnes</a></li>
                                                <li><a href="#">Private Policy</a></li>
                                                <li><a href="#">Site Map</a></li>')
                                        ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-4 hidden-sm col-xs-12">
                            <div class="single-footer instagrm-area">
                                <div class="footer-title uppercase">
                                    <h5><?php echo $this->MelisTag($this->SiteConfig('homePageId'), "footer_title_3", 'textarea', 'InstaGram')?></h5>
                                </div>
                                <?php 
                                    echo $this->MelisTag($this->SiteConfig('homePageId'), 'footer_text_3', 'html',
                                    '<div class="instagrm">
                                        <ul>
                                            <li><a href="#"><img src="'.$this->basePath('/MelisDemoCommerce/images/gallery/01.jpg').'" alt=""></a></li>
                                            <li><a href="#"><img src="'.$this->basePath('/MelisDemoCommerce/images/gallery/02.jpg').'" alt=""></a></li>
                                            <li><a href="#"><img src="'.$this->basePath('/MelisDemoCommerce/images/gallery/03.jpg').'" alt=""></a></li>
                                            <li><a href="#"><img src="'.$this->basePath('/MelisDemoCommerce/images/gallery/04.jpg').'" alt=""></a></li>
                                            <li><a href="#"><img src="'.$this->basePath('/MelisDemoCommerce/images/gallery/05.jpg').'" alt=""></a></li>
                                            <li><a href="#"><img src="'.$this->basePath('/MelisDemoCommerce/images/gallery/06.jpg').'" alt=""></a></li>
                                        </ul>
                                    </div>')
                                ?>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-4 col-lg-offset-1 col-xs-12">
                            <div class="social-icon socile-icon-style-3">
                                <div class="footer-title uppercase">
                                    <h5><?php echo $this->MelisTag($this->SiteConfig('homePageId'), "footer_title_4", 'textarea', 'Social Network')?></h5>
                                </div>
                                <ul>
                                    <li><a href="https://www.facebook.com/melistechnology" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
                                    <li><a href="https://twitter.com/meliscms" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
                                    <li><a href="https://www.linkedin.com/company/melis-technology" target="_blank"><i class="zmdi zmdi-linkedin"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--footer area start-->
            
            <!--footer bottom area start-->
            <div class="footer-bottom global-table">
                <div class="global-row">
                    <div class="global-cell">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="site-note">
                                        <p>All of this demo website images are used under license from Shutterstock.com. It is strictly forbidden to reuse or reproduce them for any other use, even personal.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--footer bottom area end-->
        </div> 
        <!-- Body main wrapper end -->
        
        <?php 
            /* Placed js at the end of the document so the pages load faster */
            // Render Page JS from Controller Action of the page
            if (is_array($this->pageJs)){
                for ($i = 0 ; $i < count($this->pageJs); $i++){
                    $this->inlineScript()->appendFile($this->pageJs[$i]);
                }
            }
            
            // Generate JS
            echo $this->inlineScript();
            
        ?>
        <script type="text/javascript">
            var newsMenuHeight = $('.news-menu-area').height();
            $('.news-menu-area .single-mega-item.coloum-4').addClass("line");
            $('.news-menu-area .single-mega-item.coloum-4.line').css({'height': newsMenuHeight});
        </script>
    </body>
</html>