<?php
$message    = $this->email_content;

$xmlDoc     = new \DOMDocument();
$xmlDoc->loadHTML($message);
$searchNode = $xmlDoc->getElementsByTagName('a');
$link       = '/';
foreach($searchNode as $node) {
    $link = $node->getAttribute('href');
}
$domain = $this->email_content_tag_replace['domain'].'/';

$messageArray = explode('<a', $message);
$message = $messageArray[0];

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

    <title>Melis Ecommerce - Responsive Email Template</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700|Lato:400' rel='stylesheet' type='text/css'>

    <!--  General CSS  -->
    <style type="text/css">
        html{
            width: 100%;
        }

        body{
            margin: 0;
            padding: 0;
            -webkit-font-smoothing: antialiased;
            mso-margin-top-alt:0px;
            mso-margin-bottom-alt:0px;
            mso-padding-alt: 0px 0px 0px 0px;
            background: #f5f5f5;
        }

        p,h1,h2,h3,h4{
            margin-top:0;
            margin-bottom:0;
            padding-top:0;
            padding-bottom:0;
        }

        table{
            font-size: 14px;
            border: 0;
        }

        img{
            border: none!important;
        }
    </style>

    <!--  Responsive CSS  -->
    <style type="text/css">
        @media only screen and (max-width: 600px) {
            body[yahoo] .full_width {width:90% !important;}
        }

        @media only screen and (max-width: 700px) {
            body[yahoo] .full_width_col {width:100% !important;}
            body[yahoo] .txt_center {text-align:center !important;}
            body[yahoo] .separator {height: 40px !important;}
        }
    </style>

</head>
<body style="margin: 0; padding: 0;" yahoo="fix">

<!--  Header  -->
<table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#f5f5f5" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border:0;">
    <tr>
        <td>

            <table class="full_width_col" width="100%" border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" style="margin: 15px auto 0 auto; width: 600px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border:0; background-color:#ffffff;">
                <tr><td height="25" width="100%" style="height:25px;"></td></tr>
                <tr>
                    <td>

                        <!--  Header Logo  -->
                        <table class="full_width_col txt_center" width="150" align="left" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border:0;">
                            <tr>
                                <td style="padding: 0 15px 0 15px">
                                    <a href="#">
                                        <img src="<?= $domain; ?>MelisDemoCommerce/images/mail/images/melis-logo-cms.png" alt="Melis Ecommerce Demo" title="Melis Ecommerce Demo" border="0" style="color: #595959; font-family: Helvetica, Arial, sans-serif; font-size: 22px;"/>
                                    </a>
                                </td>
                            </tr>
                            <tr><td class="separator" height="1" width="1"></td></tr>
                        </table>
                        <!--  End Header Logo  -->


                    </td>
                </tr>
                <tr>
                    <td>
                        <!--  Content  -->
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" align="center" bgcolor="ffffff" style="margin: 0 auto 0 auto; width: 100%;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border:0; background-color:#ffffff;">
                            <tr><td height="80" width="100%" style="height:80px;"></td></tr>
                            <tr>
                                <td align="center">

                                    <table class="full_width" width="600" border="0" cellpadding="0" cellspacing="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border:0; text-align:left;">
                                        <tr>
                                            <td style="padding: 0 15px 0 15px;">
                                                <img src="<?= $domain; ?>MelisDemoCommerce/images/mail/images/icon_lock.jpg" border="0" style="margin: 0 auto; display: block;"/>
                                            </td>
                                        </tr>
                                        <tr><td height="50" width="100%" style="height:40px;"></td></tr>
                                        <tr>
                                            <td style="padding: 0 15px 0 15px; text-align: center; color: #333333; font-family: 'Montserrat', Helvetica, Arial, sans-serif; font-size: 24px; font-weight: 900; letter-spacing:1.85px; text-transform:uppercase;">
                                                Forgot
                                            </td>
                                        </tr>
                                        <tr><td height="15" width="100%" style="height:15px;"></td></tr>
                                        <tr>
                                            <td style="padding: 0 15px 0 15px; text-align: center; color: #333333; font-family: 'Montserrat', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 700; letter-spacing:1.85px; text-transform:uppercase;">
                                                Your Password?
                                            </td>
                                        </tr>
                                        <tr><td height="30" width="100%" style="height:30px;"></td></tr>
                                        <tr>
                                            <td style="padding: 0 15px 0 15px; text-align: center; color: #333333; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 700; letter-spacing:0.4px; line-height: 1.6;">
                                                <?= $message; ?>
                                            </td>
                                        </tr>
                                        <tr><td height="50" width="100%" style="height:50px;"></td></tr>
                                        <tr>
                                            <td style="padding: 0 15px 0 15px; text-align: center; color: #333333; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 700; letter-spacing:0.4px;">
                                                <a class="btn" style="background: #6a1400; color: #fff; font-family: 'Montserratt', Helvetica, Arial, sans-serif; font-size: 14px; text-decoration: none; height: 50px; line-height: 50px; display: inline-block; padding: 0 40px; border-radius: 4px; text-transform: uppercase; letter-spacing: 1.4px; font-weight: 700;" href="<?= $link; ?>">Reset password</a>
                                            </td>
                                        </tr>
                                        <tr><td height="80" width="100%" style="height:80px;"></td></tr>
                                    </table>

                                </td>
                            </tr>
                            <tr><td height="40" width="100%" style="height:40px;"></td></tr>
                        </table>
                        <!--  End Content  -->
                    </td>
                </tr>
                <tr>
                    <td>
                        <!--  Footer  -->
                        <table class="full_width_700" border="0" cellpadding="0" cellspacing="0" width="100%" align="center" bgcolor="333333" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border:0; background-color:#333333; border-top: 5px; border-top-style: solid; border-top-color: #f7f6f6;">
                            <tr>
                                <td align="center">

                                    <table class="full_width_col" width="600" border="0" cellpadding="0" cellspacing="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border:0;">
                                        <tr><td height="15" width="100%" style="height:15px;"></td></tr>
                                        <tr>
                                            <td>

                                                <!--  Copyrights  -->
                                                <table class="full_width_col txt_center" width="400" border="0" cellpadding="0" cellspacing="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border:0; text-align:center;">
                                                    <tr>
                                                        <td style="color: #ffffff; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 12px; font-weight: 400; letter-spacing: 0.25px">
                                                            Copyright ©2017 Melis Technology, All Rights Reserved
                                                        </td>
                                                    </tr>
                                                </table>
                                                <!--  End Copyrights  -->

                                            </td>
                                        </tr>
                                    </table>

                                </td>
                            </tr>
                            <tr><td height="15" width="100%" style="height:15px;"></td></tr>
                        </table>
                        <!--  End Footer  -->
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<!--  End Header  -->


</body>
</html>